version 1.0

#prefix name should be autogenerated from the input bam rather than specifying in the input.json

task markduplicates {
    input {
        String SID
        File input_bam

        Int memory
        Int disk_space
        Int ncpu
        Boolean use_e2 = false
        Int preemptible
        String docker
    }

    String output_bam = sub(basename(input_bam), "\\.bam$", ".md.bam")

    Int e2_cpu = 2 * ceil(if ncpu / 2.0 > memory / 16.0 then ncpu / 2.0 else memory / 16.0)

    command <<<
        set -euo pipefail
        echo "--- $(date "+[%b %d %H:%M:%S]") Running ulimit ---"
        ulimit -c unlimited

        echo "--- $(date "+[%b %d %H:%M:%S]") Done with ulimit, running markduplicates ---"
        ln -s /dev/null ~{output_bam}
        # UMI-appended QNAMEs do not match Picard's Illumina coordinate parser.
        picard -Xmx32g MarkDuplicates \
            I=~{input_bam} \
            O=~{output_bam} \
            CREATE_INDEX=false \
            COMPRESSION_LEVEL=0 \
            VALIDATION_STRINGENCY=SILENT \
            ASSUME_SORT_ORDER=coordinate \
            READ_NAME_REGEX=null \
            M=~{SID}.marked_dup_metrics.txt \
            REMOVE_DUPLICATES=true

        [[ -L ~{output_bam} ]]
        echo "--- $(date "+[%b %d %H:%M:%S]") Done with markduplicates, finished task ---"
    >>>

    output {
        File metrics = "${SID}.marked_dup_metrics.txt"
    }

    runtime {
        cpu: ncpu
        memory: "${memory}GB"
        disks: "local-disk ${disk_space} HDD"
        docker: docker
        gcp: if use_e2 then object { predefinedMachineType: "e2-custom-${e2_cpu}-${memory * 1024}" } else object {}
        preemptible: preemptible
    }

    parameter_meta {
        SID: {
            type: "id"
        }
        input_bam: {
            label: "Mapped/Aligned Reads BAM File"
        }
    }

    meta {
        author: "Archana Raja"
    }
}
